// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr-T9pUtHf24qOUsMvUvkRnIrugvQuQ1Y',
    appId: '1:54631553524:web:176359679f2177d7f401a1',
    messagingSenderId: '54631553524',
    projectId: 'project-al-mobile-apps',
    authDomain: 'project-al-mobile-apps.firebaseapp.com',
    storageBucket: 'project-al-mobile-apps.firebasestorage.app',
    measurementId: 'G-D4QCMZJR52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPAppCKmZe0-hxcHZMDFvtPH_RhE1nbyo',
    appId: '1:54631553524:android:b6943e4c82eb8ae7f401a1',
    messagingSenderId: '54631553524',
    projectId: 'project-al-mobile-apps',
    storageBucket: 'project-al-mobile-apps.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZUayC7Jlv633YOYlrHM8WphEIj6yhDrI',
    appId: '1:54631553524:ios:36e436baececfa90f401a1',
    messagingSenderId: '54631553524',
    projectId: 'project-al-mobile-apps',
    storageBucket: 'project-al-mobile-apps.firebasestorage.app',
    iosBundleId: 'com.example.cultulingo',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZUayC7Jlv633YOYlrHM8WphEIj6yhDrI',
    appId: '1:54631553524:ios:36e436baececfa90f401a1',
    messagingSenderId: '54631553524',
    projectId: 'project-al-mobile-apps',
    storageBucket: 'project-al-mobile-apps.firebasestorage.app',
    iosBundleId: 'com.example.cultulingo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr-T9pUtHf24qOUsMvUvkRnIrugvQuQ1Y',
    appId: '1:54631553524:web:b0a81435b2083979f401a1',
    messagingSenderId: '54631553524',
    projectId: 'project-al-mobile-apps',
    authDomain: 'project-al-mobile-apps.firebaseapp.com',
    storageBucket: 'project-al-mobile-apps.firebasestorage.app',
    measurementId: 'G-BS8WVRQT17',
  );
}
